server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 默认情况下 Eureka Server 会向自己注册，设为 false 防止自己注册自己
    fetch-registry: false # 默认情况下 Eureka Server 会向自己注册，设为 false 防止自己注册自己
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server