server:
  port: 8011


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

spring:
  application:
    name: eureka-client

  zipkin:
    base-url: http://localhost:9411 # Zipkin Server 地址
  sleuth:
    sampler:
      probability: 1.0 # 以 100% 的概率将链路的数据上传给 Zipkin Server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
